name = "SimpleBenders"
uuid = "b3995708-6e75-11e9-263f-69b1eca53229"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
description = "A simple Benders algorithm based on JuMP"
version = "0.1.1"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
JuMP = "1.8"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["HiGHS", "LinearAlgebra", "Test"]
