name = "SimpleBenders"
uuid = "b3995708-6e75-11e9-263f-69b1eca53229"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
description = "A simple Benders algorithm based on JuMP"
version = "0.1.1"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
JuMP = "0.21"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Clp", "Cbc", "Test"]
